version: "2"

run:
  timeout: 5m
  go: "1.23"

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - k8s.io
        - sigs.k8s.io
        - github.com/kausality-io/kausality

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
